# Generated by Django 5.2.7 on 2025-11-29 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_rename_genero_pelicula_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pelicula',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='peliculas'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='anio',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='pelicula',
            field=models.CharField(max_length=100),
        ),
    ]
